"""Add all tables

Revision ID: 77337f105605
Revises:
Create Date: 2020-07-23 02:42:30.021942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77337f105605'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'User',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('username', sa.String(length=255), nullable=False),
        sa.Column('password', sa.String(length=255), nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default='1', nullable=True),
        sa.Column('is_anonymous', sa.Boolean(), server_default='0', nullable=True),
        sa.Column('is_authenticated', sa.Boolean(), server_default='1', nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username')
    )
    op.create_table(
        'AuthorizationCode',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('code', sa.String(length=255), nullable=False),
        sa.Column('expires_at', sa.Integer(), nullable=False),
        sa.Column('redirect_uri', sa.String(length=255), nullable=False),
        sa.Column('u_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['u_id'], ['User.id'], onupdate='CASCADE',
                                ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
    )
    op.create_table(
        'RefreshToken',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('token', sa.String(length=255), nullable=False),
        sa.Column('u_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['u_id'], ['User.id'], onupdate='CASCADE',
                                ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('token')
    )
    op.create_table(
        'AccessToken',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('expires_at', sa.Integer(), nullable=False),
        sa.Column('refresh_token_id', sa.Integer(), nullable=False),
        sa.Column('token', sa.String(length=255), nullable=False),
        sa.Column('u_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['refresh_token_id'], ['RefreshToken.id'],
                                onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['u_id'], ['User.id'], onupdate='CASCADE',
                                ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AccessToken')
    op.drop_table('RefreshToken')
    op.drop_table('AuthorizationCode')
    op.drop_table('User')
    # ### end Alembic commands ###
